### ISSUE TITLE
Can I get an invite to the slack community? 

### ISSUE THREAD

**Issue by iDVB** [winadminsdotorg/WindowsAdmins#1]
The request access form at:
https://slofile.com/slack/winadmins

Doesn't work.
![image](https://user-images.githubusercontent.com/189506/42516090-4924bcf0-842b-11e8-909d-5dd5f0056df8.png)

**Comment by PsychoData** [comment]
@iDVB Hey,  sorry for the late notice. 
That link is older now, we've gone through a few variations. 

https://aka.ms/winadmins is the latest one and we are working to try to keep it up to date.

**Comment by anthony-fontanez** [comment]
The Slofile page has been updated to point to https://aka.ms/winadmins
